### ISSUE TITLE
Backwards "obsolete" relationship in FO3 binoculars mods

### ISSUE THREAD

**Issue by hoxia** [loot/fallout3#82]
Two mods by the same author, the later of which includes the entirety of the earlier mod (checked with FO3edit) plus additional content (scopes and related workbench recipes). Note the Nexus mod page number, "8909" vs "8936".

https://loot.github.io/search/?game=fallout3&search=binoculars

Currently the later, larger mod is marked as an obsolete version of the earlier mod. This is possibly because the "version number" of the earlier version is higher, while the later, expanded mod began with a lower version number.

**Comment by Freso** [comment]
He doesn't state on either one of them that the other is newer than the other. "Binoculars" 2.0 was uploaded 2009-09-11 and "Binoculars and Portable Scopes" 1.2 was uploaded on 2009-09-10. I'm tempted to just remove the "obsolete" message entirely—or maybe replacing it with a mutually `inc`ompatible flag since it seems like they do basically the same thing, just one is more expansive than the other.

Can someone open these up in FO3Edit and check if they have conflicting records in addition to just the loose files?

**Comment by MacSplody** [comment]
> Two mods by the same author, the later of which includes the entirety of the earlier mod (checked with FO3edit) plus additional content (scopes and related workbench recipes).

> Can someone open these up in FO3Edit and check if they have conflicting records in addition to just the loose files?

`Binoculars and Scopes.esp` does include `Binoculars.esp`. So a useOnlyOne and an already included in message would do.

![image](https://user-images.githubusercontent.com/1944639/63902933-9e3cad00-ca03-11e9-9195-cb1e28404ae9.png)
